[package]
name = "bo-srv-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "import"

[dependencies]
chrono = "0.4.34"
datetime = "0.5.2"
reqwest = { version = "0.11.24" , features = ["blocking"] }
tokio = "1.36.0"
